// Generated by scripts/vite-plugin-wp-assets.mjs from resources/blocks/*/readme.md.
// Do not edit by hand.
import { __ } from '@wordpress/i18n';

export interface GeneratedBlockHelp {
	description: string;
	controls: Record< string, string >;
	tips: string[];
}

export const GENERATED_BLOCK_HELP: Record< string, GeneratedBlockHelp > = {
	"box": {
		description: __( "Box is the generic styled wrapper for cards, panels, and manual layouts. Use it when Section, Stack, and Grid are too opinionated and you need one element with the full Blicks styling system.", 'blicks' ),
		controls: {
			"blicks": __( "Stores the full Blicks style tree for layout, spacing, border, position, color, background, typography, and effects controls.", 'blicks' ),
			"tag": __( "Chooses the HTML element for the wrapper. Use `div` for generic layout, `article` for repeatable cards, `aside` for supporting content, and `figure` for media groups.", 'blicks' )
		},
		tips: [ __( "Use Box inside Grid for pricing cards, feature cards, and other repeated panels.", 'blicks' ), __( "Use Section for page bands; use Box for the smaller wrappers inside those bands.", 'blicks' ) ],
	},
	"button": {
		description: __( "Button renders a clickable action. It can output a real button when no URL is set or a link-style button when a URL is provided.", 'blicks' ),
		controls: {
			"text": __( "The visible button label.", 'blicks' ),
			"url": __( "The destination URL. When set, the block renders as an anchor so it can navigate like a link.", 'blicks' ),
			"linkTarget": __( "Controls whether the link opens in the same tab or a new tab.", 'blicks' ),
			"rel": __( "Sets relationship attributes for link output, such as `nofollow` or `noopener`.", 'blicks' ),
			"variant": __( "Chooses the visual style: primary/default, secondary, outline, ghost, destructive, or link.", 'blicks' ),
			"size": __( "Chooses the button size preset.", 'blicks' ),
			"icon": __( "Adds an optional built-in icon.", 'blicks' ),
			"iconPosition": __( "Places the icon before or after the label.", 'blicks' )
		},
		tips: [ __( "Use one primary button per section when possible.", 'blicks' ), __( "Use outline or secondary variants for supporting actions.", 'blicks' ), __( "If the button navigates, set a URL; if it triggers an interaction, leave the URL empty.", 'blicks' ) ],
	},
	"buttons": {
		description: __( "Buttons is a container that lays out one or more Button blocks in a row or column with shared alignment, spacing, and wrapping. Only Button blocks can be placed inside it.", 'blicks' ),
		controls: {
			"orientation": __( "Arranges the buttons horizontally (a row) or vertically (a column).", 'blicks' ),
			"gap": __( "Sets the space between buttons using the spacing scale (XS–LG).", 'blicks' ),
			"justify": __( "Distributes the buttons along the main axis: start, center, end, or space-between.", 'blicks' ),
			"wrap": __( "Allows buttons to wrap onto multiple lines when they run out of room, or keeps them on a single line.", 'blicks' )
		},
		tips: [ __( "Use a horizontal row with a Start or Center distribution for a typical primary/secondary action pair.", 'blicks' ), __( "Switch to vertical orientation for stacked calls-to-action on narrow layouts.", 'blicks' ), __( "Pair one default (primary) Button with an outline or ghost Button for a clear visual hierarchy.", 'blicks' ) ],
	},
	"divider": {
		description: __( "Divider renders a semantic separator. Use it to separate related content groups, card sections, pricing features, or long page areas.", 'blicks' ),
		controls: {
			"orientation": __( "Chooses a horizontal or vertical divider.", 'blicks' ),
			"thickness": __( "Sets the divider line thickness.", 'blicks' ),
			"lineStyle": __( "Chooses the line style: solid, dashed, dotted, or none.", 'blicks' ),
			"color": __( "Sets the divider color.", 'blicks' )
		},
		tips: [ __( "Use Divider when the separation is meaningful, not purely decorative.", 'blicks' ), __( "Pair it with spacing so the line has room to breathe.", 'blicks' ), __( "Use border tokens for dividers that should match the theme.", 'blicks' ) ],
	},
	"grid": {
		description: __( "Grid arranges child blocks in columns. Use it for feature cards, pricing cards, galleries, comparison panels, and any layout where multiple items should align in a repeated structure.", 'blicks' ),
		controls: {
			"columns": __( "Sets the number of equal-width columns when auto-fit is off.", 'blicks' ),
			"autoFit": __( "Lets the grid create as many columns as fit the available width. This is useful for responsive card collections.", 'blicks' ),
			"minColumnWidth": __( "Sets the minimum column width used by auto-fit grids.", 'blicks' ),
			"gap": __( "Sets row and column spacing between grid children using Blicks spacing tokens (XS–XL).", 'blicks' ),
			"dense": __( "Allows the browser to pack grid items into earlier empty spaces when possible.", 'blicks' ),
			"tag": __( "Chooses the grid wrapper element. Use `div` for generic layout and `ul`/`ol` when the children form a list. For a full-width band, wrap the Grid in a Section block instead of changing the tag.", 'blicks' )
		},
		tips: [ __( "Use Grid for repeated sibling items, then use Stack inside each item for card content.", 'blicks' ), __( "Use two columns for pricing and comparison sections.", 'blicks' ), __( "Use auto-fit for collections that should adapt without manual breakpoint changes.", 'blicks' ) ],
	},
	"heading": {
		description: __( "Heading renders semantic H1-H6 text. Use it for page titles, section titles, card titles, and content hierarchy that should remain meaningful to readers and search engines.", 'blicks' ),
		controls: {
			"level": __( "Sets the heading level from H1 to H6. Choose the level from document structure first, then style it with typography controls if the visual size needs to differ.", 'blicks' ),
			"content": __( "The editable heading text.", 'blicks' )
		},
		tips: [ __( "Use one H1 for the main page title.", 'blicks' ), __( "Do not skip heading levels just to change visual size.", 'blicks' ), __( "Use typography controls for alignment, size, weight, and text color overrides.", 'blicks' ) ],
	},
	"icon": {
		description: __( "Icon renders a small inline SVG from the Blicks icon registry. Use it for visual emphasis, feature markers, compact labels, and UI affordances.", 'blicks' ),
		controls: {
			"icon": __( "Chooses the icon glyph.", 'blicks' ),
			"size": __( "Sets the icon size.", 'blicks' ),
			"strokeWidth": __( "Controls the line weight for stroke-based icons.", 'blicks' ),
			"label": __( "Adds an accessible label. Leave it empty when the icon is decorative.", 'blicks' )
		},
		tips: [ __( "Pair decorative icons with nearby text instead of relying on the icon alone.", 'blicks' ), __( "Add a label when the icon communicates meaning by itself.", 'blicks' ), __( "Use text color controls to make icons follow the design system.", 'blicks' ) ],
	},
	"image": {
		description: __( "Image renders a responsive figure with optional link and caption. Use it for visual content that belongs to the page structure, not for decorative backgrounds.", 'blicks' ),
		controls: {
			"id": __( "Stores the selected WordPress media ID when an image is chosen from the media library.", 'blicks' ),
			"url": __( "The image source URL.", 'blicks' ),
			"alt": __( "Alternative text for accessibility.", 'blicks' ),
			"aspectRatio": __( "Controls the displayed image ratio. Use `auto` to preserve the natural image dimensions.", 'blicks' ),
			"objectFit": __( "Controls how the image fits inside the chosen aspect ratio.", 'blicks' ),
			"linkTo": __( "Chooses whether the image links nowhere, to the media file, or to a custom URL.", 'blicks' ),
			"href": __( "The custom destination when `linkTo` is set to custom.", 'blicks' ),
			"caption": __( "Optional figure caption.", 'blicks' )
		},
		tips: [ __( "Write alt text for meaningful images; leave it empty only when the image is decorative.", 'blicks' ), __( "Use aspect ratio for consistent card and grid layouts.", 'blicks' ), __( "Use Background controls on Section or Box for decorative imagery.", 'blicks' ) ],
	},
	"section": {
		description: __( "Section is the full-bleed page band. It renders a fixed semantic `<section>` for background, surface, spacing, and block styling, plus an inner content wrapper whose width, min width, and max width are controlled directly.", 'blicks' ),
		controls: {
			"sectionWidth": __( "Sets the outer section width. Keep `auto` for normal WordPress full-width alignment behavior, or use a CSS length when the section itself needs a specific width.", 'blicks' ),
			"sectionHeight": __( "Sets the outer section minimum height. Keep `auto` for content-driven height, or use values like `80vh`, `600px`, or `100svh` for viewport-based bands without clipping wrapped content.", 'blicks' ),
			"contentWidth": __( "Sets the inner content wrapper width.", 'blicks' ),
			"contentMinWidth": __( "Sets the inner content wrapper minimum width.", 'blicks' ),
			"contentMaxWidth": __( "Sets the inner content wrapper maximum width. The default follows `var(--blicks-content-size, var(--wp--style--global--content-size, 1200px))` so the section stays aligned with the active design system or the active WordPress theme layout.", 'blicks' ),
			"surface": __( "Applies a preset treatment to the full-bleed outer section. Use `plain` for invisible structure, `muted` for soft bands, `card` for elevated panels, and `outline` for bordered groups.", 'blicks' ),
			"sectionSpace": __( "Applies vertical padding to the outer section. Use it for page rhythm before reaching for manual spacing controls.", 'blicks' )
		},
		tips: [ __( "Prefer Section for root-level page bands and major layout areas.", 'blicks' ), __( "Put Stack or Grid inside Section for content layout.", 'blicks' ), __( "The outer section owns the background; the inner wrapper owns content sizing.", 'blicks' ) ],
	},
	"spacer": {
		description: __( "Spacer adds intentional empty space. Use it sparingly to create rhythm between sections or to reserve space in utility layouts.", 'blicks' ),
		controls: {
			"size": __( "Sets the spacer dimension.", 'blicks' ),
			"orientation": __( "Chooses whether the spacer creates vertical or horizontal space.", 'blicks' )
		},
		tips: [ __( "Prefer Section spacing and Stack/Grid gaps before adding Spacer blocks.", 'blicks' ), __( "Use Spacer for exceptional layout rhythm, not as the default spacing system.", 'blicks' ), __( "Keep spacer values token-like and consistent across a page.", 'blicks' ) ],
	},
	"stack": {
		description: __( "Stack arranges child blocks in one direction. Use it for vertical content groups, horizontal action rows, navigation groups, and simple card internals where items need predictable spacing.", 'blicks' ),
		controls: {
			"orientation": __( "Sets the main axis. `Vertical` stacks children top to bottom; `Horizontal` places children in a row.", 'blicks' ),
			"tag": __( "Chooses the wrapper element. Use `div` for generic layout, `section` for meaningful groups, `nav` for navigation, and `ul` when the children form a list.", 'blicks' ),
			"gap": __( "Sets the spacing between children using Blicks spacing tokens.", 'blicks' ),
			"align": __( "Controls cross-axis alignment. In a vertical stack it affects horizontal child alignment; in a horizontal stack it affects vertical alignment.", 'blicks' ),
			"justify": __( "Controls main-axis distribution. Use it when the stack has extra space and children need to group, spread, or center.", 'blicks' ),
			"wrap": __( "Allows horizontal stacks to wrap onto multiple lines when space gets tight.", 'blicks' )
		},
		tips: [ __( "Use Stack inside cards, heroes, headers, and form-like groups.", 'blicks' ), __( "Use horizontal Stack for buttons and compact metadata rows.", 'blicks' ), __( "Use Grid instead when children need columns, rows, or equal-width tracks.", 'blicks' ) ],
	},
	"text": {
		description: __( "Text renders a rich paragraph. Use it for body copy, descriptions, captions, feature text, short notes, and supporting content.", 'blicks' ),
		controls: {
			"content": __( "The editable paragraph content. Supports inline formatting such as bold, italic, and links.", 'blicks' )
		},
		tips: [ __( "Keep Text blocks focused; use multiple Text blocks instead of one long mixed-purpose paragraph.", 'blicks' ), __( "Pair Text with Heading inside Stack for consistent content groups.", 'blicks' ), __( "Use typography controls for alignment and text styling instead of adding custom classes.", 'blicks' ) ],
	}
};
