<?php
/**
 * Strict validation for user-supplied custom HTML attributes and style output.
 *
 * @package Blicks
 */

declare(strict_types=1);

namespace Blicks\Style;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Strict validation/sanitization for the Advanced-tab custom HTML attributes, plus the guard that
 * keeps generated CSS from breaking out of a `<style>` element. **Authoritative front-end gate.**
 * Mirror of `resources/framework/sanitize.ts` — keep the two byte-compatible
 * (parity: tests/Unit/Style/SanitizeTest.php ⇄ sanitize.test.ts).
 */
final class Sanitize {

	private const ATTR_NAME_RE   = '/^(?:data-[a-z0-9-]+|aria-[a-z-]+|role|title|id|lang|dir)$/';
	private const CONTROL_CHARS  = '/[\x00-\x1F\x7F]/';
	private const SCRIPT_SCHEME  = '/(?:javascript|vbscript)\s*:/i';
	private const ATTR_VALUE_MAX = 500;

	/** Normalised (lowercased) attribute name, or null if disallowed. */
	public static function attrName( string $name ): ?string {
		$n = strtolower( trim( $name ) );
		return 1 === preg_match( self::ATTR_NAME_RE, $n ) ? $n : null;
	}

	/** Strip control chars + dangerous URL schemes, cap length. */
	public static function attrValue( string $value ): string {
		$v = (string) preg_replace( self::CONTROL_CHARS, '', $value );
		$v = (string) preg_replace( self::SCRIPT_SCHEME, '', $v );
		$v = trim( $v );
		if ( mb_strlen( $v ) > self::ATTR_VALUE_MAX ) {
			$v = mb_substr( $v, 0, self::ATTR_VALUE_MAX );
		}
		return $v;
	}

	/**
	 * Validate a list of `{name,value}` rows → name => value (valid only, last write wins).
	 *
	 * @param mixed $list
	 * @return array<string,string>
	 */
	public static function attributes( $list ): array {
		if ( ! is_array( $list ) ) {
			return [];
		}
		$out = [];
		foreach ( $list as $item ) {
			if ( ! is_array( $item ) ) {
				continue;
			}
			$name = self::attrName( (string) ( $item['name'] ?? '' ) );
			if ( null === $name ) {
				continue;
			}
			$out[ $name ] = self::attrValue( (string) ( $item['value'] ?? '' ) );
		}
		return $out;
	}

	/**
	 * Keep generated CSS safe inside a `<style>` element without HTML-escaping valid selectors.
	 * The payload is machine-generated by the style engine, but it interpolates user-entered
	 * token values, so a stray `</style` must never be able to close the element.
	 */
	public static function styleTagContent( string $css ): string {
		return (string) preg_replace( '/<\/\s*style/i', '<\/style', $css );
	}
}
