#!/usr/bin/env node
/**
 * Generates the curated Lucide icon registry from `scripts/icon-set.json`.
 *
 * Outputs:
 *   - resources/framework/icons/lucide.gen.ts   (registers itself with the icon registry)
 *   - resources/framework/icons/names.gen.json  (PHP-readable allowlist + aliases)
 *
 * Run via `pnpm gen:icons` (also auto-runs before `pnpm build`/`pnpm dev`).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT      = resolve( dirname( fileURLToPath( import.meta.url ) ), '..' );
const SET_PATH  = resolve( ROOT, 'scripts/icon-set.json' );
const LUCIDE    = resolve( ROOT, 'node_modules/lucide-static' );
const TAGS_PATH = resolve( LUCIDE, 'tags.json' );
const ICONS_DIR = resolve( LUCIDE, 'icons' );
const OUT_TS    = resolve( ROOT, 'resources/framework/icons/lucide.gen.ts' );
const OUT_JSON  = resolve( ROOT, 'resources/framework/icons/names.gen.json' );
const LICENSE_PATH = resolve( LUCIDE, 'LICENSE' );

if ( ! existsSync( LUCIDE ) ) {
	console.error( 'lucide-static is not installed. Run `pnpm install`.' );
	process.exit( 1 );
}

const set  = JSON.parse( readFileSync( SET_PATH, 'utf8' ) );
const tags = JSON.parse( readFileSync( TAGS_PATH, 'utf8' ) );
const lucideLicense = readFileSync( LICENSE_PATH, 'utf8' ).trim();

/** Convert kebab-case to a human label: "arrow-up-right" → "Arrow up right". */
function toLabel( slug ) {
	return slug.replace( /-/g, ' ' ).replace( /^\w/, ( c ) => c.toUpperCase() );
}

/** Extract the inner contents of the lucide SVG (drop the outer <svg ...> wrapper + the license comment). */
function readSvgInner( slug ) {
	const file = resolve( ICONS_DIR, `${ slug }.svg` );
	if ( ! existsSync( file ) ) return null;
	const raw = readFileSync( file, 'utf8' );
	const match = raw.match( /<svg\b[^>]*>([\s\S]*?)<\/svg>/ );
	if ( ! match ) return null;
	return match[ 1 ]
		.replace( /\n/g, '' )
		.replace( /\s{2,}/g, ' ' )
		.replace( /\s*\/>/g, '/>' )
		.trim();
}

const entries  = [];
const missing  = [];
const seen     = new Set();
const allNames = [];

for ( const [ category, names ] of Object.entries( set.categories ) ) {
	for ( const name of names ) {
		if ( seen.has( name ) ) continue;          // dedupe — same icon can appear in two categories
		seen.add( name );
		const inner = readSvgInner( name );
		if ( ! inner ) { missing.push( name ); continue; }
		const keywords = Array.isArray( tags[ name ] ) ? tags[ name ] : [];
		entries.push( { name, category, label: toLabel( name ), keywords, svg: inner } );
		allNames.push( name );
	}
}

if ( missing.length ) {
	console.warn( `gen-icons: skipped ${ missing.length } missing icon(s): ${ missing.join( ', ' ) }` );
}

// Validate aliases — each alias must point to a name we emitted.
const aliases = {};
for ( const [ alias, target ] of Object.entries( set.aliases ?? {} ) ) {
	if ( ! seen.has( target ) ) {
		console.warn( `gen-icons: alias "${ alias }" → "${ target }" skipped (target not in set)` );
		continue;
	}
	aliases[ alias ] = target;
}

// --- emit TS ---
// Data only — registration happens in `./bootstrap` so `index.ts` stays free of
// circular-import TDZ pitfalls.
const ts = [
	'// This file is auto-generated by `pnpm gen:icons`. Do not edit by hand.',
	'// Source allowlist: scripts/icon-set.json',
	'//',
	...lucideLicense.split( '\n' ).map( ( line ) => `// ${ line }` ),
	"import type { IconDef } from './index';",
	'',
	'export const LUCIDE_ICONS: Record< string, IconDef > = {',
	...entries.map( ( e ) => {
		const label    = JSON.stringify( e.label );
		const keywords = JSON.stringify( e.keywords );
		const category = JSON.stringify( e.category );
		const svg      = JSON.stringify( e.svg );
		return `\t${ JSON.stringify( e.name ) }: { label: ${ label }, category: ${ category }, keywords: ${ keywords }, svg: ${ svg } },`;
	} ),
	'};',
	'',
].join( '\n' );

writeFileSync( OUT_TS, ts );

// --- emit JSON (consumed by PHP UiGenerator + JS validators if needed) ---
writeFileSync( OUT_JSON, JSON.stringify( {
	library:  'lucide',
	version:  set.version ?? null,
	count:    allNames.length,
	names:    allNames,
	aliases,
	license: {
		source: 'lucide-static',
		notice: lucideLicense,
	},
}, null, '\t' ) + '\n' );

console.log( `gen-icons: wrote ${ allNames.length } icons → ${ OUT_TS.replace( ROOT + '/', '' ) }` );
console.log( `gen-icons: wrote ${ Object.keys( aliases ).length } aliases → ${ OUT_JSON.replace( ROOT + '/', '' ) }` );
